/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface CtaComponent {
        "ctaText": string;
        "ctaTitle": string;
        "imageSearchterm": string;
        "linkText": string;
        "visible": boolean;
    }
    interface ExampleComponent {
        "exampleProp": string;
    }
}
declare global {
    interface HTMLCtaComponentElement extends Components.CtaComponent, HTMLStencilElement {
    }
    var HTMLCtaComponentElement: {
        prototype: HTMLCtaComponentElement;
        new (): HTMLCtaComponentElement;
    };
    interface HTMLExampleComponentElement extends Components.ExampleComponent, HTMLStencilElement {
    }
    var HTMLExampleComponentElement: {
        prototype: HTMLExampleComponentElement;
        new (): HTMLExampleComponentElement;
    };
    interface HTMLElementTagNameMap {
        "cta-component": HTMLCtaComponentElement;
        "example-component": HTMLExampleComponentElement;
    }
}
declare namespace LocalJSX {
    interface CtaComponent {
        "ctaText"?: string;
        "ctaTitle"?: string;
        "imageSearchterm"?: string;
        "linkText"?: string;
        "visible"?: boolean;
    }
    interface ExampleComponent {
        "exampleProp"?: string;
    }
    interface IntrinsicElements {
        "cta-component": CtaComponent;
        "example-component": ExampleComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "cta-component": LocalJSX.CtaComponent & JSXBase.HTMLAttributes<HTMLCtaComponentElement>;
            "example-component": LocalJSX.ExampleComponent & JSXBase.HTMLAttributes<HTMLExampleComponentElement>;
        }
    }
}
